### ISSUE TITLE
multi-account usage: sort new tweets by date no matter which account they come from?

### ISSUE THREAD

**Issue by kr428** [mariotaku/twidere#230]
Using Twidere with two accounts, one being Twitter, one being Friendica/StatusNet. Overally this works pretty good except for a minor issue(?): No matter whether in start page or mentions tab, I always see "recent" tweets / messages in account 1, then got to scroll far down to eventually find the "recent" tweets or messages in account 2. Shouldn't they all per default be chronologically sorted?

**Comment by mariotaku** [comment]
Added in recent versions.
