### ISSUE TITLE
Allow users to rearrange the tab order

### ISSUE THREAD

**Issue by Quintasan** [mariotaku/twidere#250]
In the Tabs section there is no way to reorder the tabs without removing them and readding them in the proper order. Frankly speaking this is annoying and should be fixed.

**Comment by mariotaku** [comment]
Which version? Recent versions should be fine, just drag on handle on the left.

**Comment by Quintasan** [comment]
Haha, indeed there is a handle there. But it's invisible in 0.3-dev from
FDroid.
22 sty 2015 17:41 "Mariotaku" <notifications@github.com> napisał(a):

**Comment by mariotaku** [comment]
oh, that's weird. I'll try to fix it.

**Comment by mariotaku** [comment]
should be fixed in newest versions.
