### ISSUE TITLE
Posting tweet causes Twidere to crash

### ISSUE THREAD

**Issue by yamatt** [mariotaku/twidere#255]
As the title says. I have been using the 'report' button in Android so hopefully you have some more information available to you.

**Comment by mariotaku** [comment]
fixed in recent commits and you will receive fix within hour or two. (for issues of android version please report in https://github.com/twidereproject/Twidere-Android/issues in the future)

**Comment by yamatt** [comment]
Sorry, this is the first repo that comes up on DDG.

**Comment by mariotaku** [comment]
@yamatt Report here is still accepted but since I have plan to develop Twidere on other platforms, create issues on different repo would be better :)
