### ISSUE TITLE
Latest version regression: timeline position is never remembered anymore

### ISSUE THREAD

**Issue by VPhantom** [mariotaku/twidere#256]
I tried two different scenarios, both are consistently incorrect in the new "material redesign" version:

1. When launching Twidere initially, pulling down to get new tweets does load them, but scrolls the timeline up to the most recent one.  I have to memorize the most recent tweet before refreshing, so I can scroll back down there and continue.

2. If I scroll anywhere in the timeline, and quit the application (which I can only do with Android's "back" button), then come back, I'm positioned at the latest tweet, not where I left the application off.

Both scenarios behaved as expected (Twidere remembering position) before this latest upgrade.

As this is my only reason to use an Android Twitter client vs Twitter's web site (which stupidly doesn't remember our position) I'm hopeful that this will be an easy fix. :)

**Comment by mariotaku** [comment]
fixed in recent commits, and you will receive update soon.
