### ISSUE TITLE
Obtrusive message: "Error while refreshing ***: Network error"

### ISSUE THREAD

**Issue by loolooyyyy** [mariotaku/twidere#257]
I have enabled **background toast notification** options, but I do not always have a connection nor when I do, have access to twitter as it is probably blocked till I run on my proxification service.

So usually none of apps, including twidere, would be able to access any of *.twitter.com URL. The problem is the following message keep poping up and saying twidere has failed while trying. And it pops up 3 times, once for each category. My refresh interval is 3 minutes so you can guess how annoying it can get :D

    Error while refreshing (Timeline|Mentions|Direct Messages):
    Network error

**Comment by mariotaku** [comment]
Maybe I should only show these messages inside app or just simply disable network error message?

**Comment by loolooyyyy** [comment]
Yes I think network error messages should be totally disabled, as they are not meant to be handled by apps, not even within apps as they are system-wide issues. At most the message might be shown on top of timeline "could not fetch new tweets, check connection".

I would gladly do this myself but unfortunately I don't think I'll have access to my laptop for next few weeks! (and currently I depend on Twidere being updated on Google play itself :D )

**Comment by mariotaku** [comment]
removed all network error messages when refreshing in recent versions.
