### ISSUE TITLE
Crash at login

### ISSUE THREAD

**Issue by Louson** [mariotaku/twidere#259]
version 0.3.0-dev-fdroid on CyanogenMod11,
At login, the app crashs when I push the "connect" (or "login" or whatever it is in english) button.

3739 AndroidRuntime E Caused by: java.lang.ClassCastException: java.lang.Object[] cannot be cast to java.lang.Void[]
3739 AndroidRuntime E at org.mariotaku.twidere.activity.support.SignInActivity$SignInTask.doInBackground(SignInActivity.java:613)

----

3739           dalvikvm  W  threadid=11: thread exiting with uncaught exception (group=0x3d8f61a0)
3739     AndroidRuntime  E  FATAL EXCEPTION: pool-2-thread-1
3739     AndroidRuntime  E  Process: org.mariotaku.twidere, PID: 3739
3739     AndroidRuntime  E  java.lang.RuntimeException: An error occured while executing doInBackground()
3739     AndroidRuntime  E  	at android.os.AsyncTask$3.done(AsyncTask.java:300)
3739     AndroidRuntime  E  	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
3739     AndroidRuntime  E  	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
3739     AndroidRuntime  E  	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
3739     AndroidRuntime  E  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
3739     AndroidRuntime  E  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
3739     AndroidRuntime  E  	at java.lang.Thread.run(Thread.java:841)
3739     AndroidRuntime  E  Caused by: java.lang.ClassCastException: java.lang.Object[] cannot be cast to java.lang.Void[]
3739     AndroidRuntime  E  	at org.mariotaku.twidere.activity.support.SignInActivity$SignInTask.doInBackground(SignInActivity.java:613)
3739     AndroidRuntime  E  	at android.os.AsyncTask$2.call(AsyncTask.java:288)
3739     AndroidRuntime  E  	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
3739     AndroidRuntime  E  	... 3 more
333     ActivityManager  W  Force finishing activity org.mariotaku.twidere/.activity.support.SignInActivity

**Comment by mariotaku** [comment]
fixed. see https://github.com/TwidereProject/Twidere-Android/issues/106.

**Comment by Louson** [comment]
My fault, I did not see it, thanks !
